[package]
name = "home-assistant-companion-desktop"
version = "0.1.0"
description = "Home Assistant Companion Desktop App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "home_assistant_companion_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "unstable", "devtools", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3.6.3", features = ["sync-secret-service", "apple-native", "windows-native"] }
aes-gcm = "0.10"
base64 = "0.21"
rand = "0.8"
mdns-sd = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync", "macros"] }
urlencoding = "2.1"
sysinfo = "0.31"
starship-battery = "0.9"
reqwest = { version = "0.12", features = ["json"] }
uuid = { version = "1.11", features = ["v4"] }
hostname = "0.4"
dirs = "5"
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
futures-util = "0.3.31"
notify-rust = "4.11.7"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18.2"
